# HR Dataset Input to SQL and Observation

In [19]:
import pandas as pd

In [66]:
df = pd.read_csv("hr_raw.csv")
df_sample = df.sample(n=200000, random_state=42)
print(df_sample.isnull().sum())
print(f' The Performance_Rating column has 325 null values')
print(f' Which is {(325/len(df_sample))*100}% which is significantly small')

Employee_ID             0
Full_Name               0
Department              0
Job_Title               0
Hire_Date               0
Performance_Rating    325
Experience_Years        0
Status                  0
Work_Mode               0
Salary                  0
Year                    0
Country                 0
City                    0
Age                     0
Job_Level               0
dtype: int64
 The Performance_Rating column has 325 null values
 Which is 0.1625% which is significantly small

In [68]:
print(df_sample[df_sample['Performance_Rating'].isnull()]['Department'].value_counts(normalize=True))
print(df_sample[df_sample['Performance_Rating'].isnull()]['Job_Level'].value_counts(normalize=True))
print(df_sample[df_sample['Performance_Rating'].isnull()]['Status'].value_counts(normalize=True))

Department
Sales         0.323077
IT            0.236923
Operations    0.209231
Finance       0.132308
HR            0.098462
Name: proportion, dtype: float64
Job_Level
Junior      0.403077
Mid         0.360000
Senior      0.172308
Director    0.064615
Name: proportion, dtype: float64
Status
Active        0.898462
Resigned      0.080000
Terminated    0.021538
Name: proportion, dtype: float64

In [74]:
# Using 'Not Rated' to group the NAs on Performance Rating as they possess significant signal the help evaluate attrition.

df_sample['Performance_Rating'] = df_sample[['Performance_Rating']].fillna('Not Rated')

In [102]:
cols = ['Status', 'Department', 'Job_Title', 'Performance_Rating', 'Work_Mode', 'Job_Level', 'Country', 'City']

for columns in cols: 
    print(columns)
    print(df_sample[columns].unique())
    print('')

Status
['Active' 'Resigned' 'Terminated' 'Retired']

Department
['Sales' 'Finance' 'Operations' 'HR' 'IT']

Job_Title
['Sales Executive' 'Accountant' 'Business Development' 'Financial Analyst'
 'Operations Director' 'Operations Analyst' 'HR Manager' 'Sales Manager'
 'System Admin' 'Software Developer' 'DevOps Engineer' 'Logistics'
 'Data Engineer' 'Operations Manager' 'Regional Lead' 'CFO' 'Supply Chain'
 'Tax Specialist' 'Sales Director' 'IT Manager' 'Finance Manager'
 'Recruiter' 'Talent Specialist' 'HR Director' 'HR Coordinator']

Performance_Rating
['Needs Improvement' 'Satisfactory' 'Excellent' 'Good' 'Not Rated']

Work_Mode
['On-site' 'Hybrid' 'Remote']

Job_Level
['Senior' 'Junior' 'Mid' 'Director']

Country
['Poland' 'Netherlands' 'United Kingdom' 'Italy' 'Spain' 'Germany'
 'France']

City
['Lodz' 'Rotterdam' 'Leeds' 'Venice' 'Barcelona' 'Berlin' 'Paris' 'Turin'
 'Munich' 'Bilbao' 'Manchester' 'Madrid' 'Frankfurt' 'Valencia' 'Cologne'
 'Birmingham' 'Lyon' 'Nice' 'Warsaw' 'Marseille' 'Edinburgh' 'Eindhoven'
 'Naples' 'Toulouse' 'Milan' 'London' 'Utrecht' 'Seville' 'Amsterdam'
 'Hamburg' 'Rome' 'Poznan' 'The Hague' 'Wroclaw' 'Krakow']

In [90]:
# Job Level at top has Director and the Job title has also directors
# With that, Every Director Job Level Must have Directors on their Job Title
# If not, it will be flagged as Inconsistency 

df_sample[df_sample['Job_Level'] == 'Director'][['Job_Level','Job_Title']]

        Job_Level             Job_Title
1629054  Director     Financial Analyst
1061701  Director  Business Development
794915   Director    Software Developer
734292   Director            Accountant
916827   Director    Software Developer
...           ...                   ...
807571   Director    Software Developer
162475   Director                   CFO
1200401  Director            IT Manager
234835   Director         Sales Manager
797048   Director             Recruiter

[10022 rows x 2 columns]

In [94]:
df_sample[df_sample['Job_Title'].str.contains('Director', regex=False)][['Job_Title', 'Job_Level']]

                   Job_Title Job_Level
191144   Operations Director       Mid
394339   Operations Director    Senior
740617        Sales Director    Junior
1378144  Operations Director    Junior
1821416  Operations Director    Junior
...                      ...       ...
743620   Operations Director       Mid
1900473          HR Director    Junior
695941        Sales Director       Mid
898470   Operations Director    Junior
106648           HR Director    Senior

[23841 rows x 2 columns]

In [113]:
print(f"Experience min:{df_sample['Experience_Years'].min()}, max:{df_sample['Experience_Years'].max()}")
print(f"Salary min:{df_sample['Salary'].min()}, max:{df_sample['Salary'].max()}")
print(f"Age min:{df_sample['Age'].min()}, max:{df_sample['Age'].max()}")
print(f"Hire Date min:{df_sample['Hire_Date'].min()}, max:{df_sample['Hire_Date'].max()}")
print(f"Year min:{df_sample['Year'].min()}, max:{df_sample['Year'].max()}")

Experience min:-5, max:30
Salary min:-99900.0, max:322107.0
Age min:21, max:66
Hire Date min:2008-03-24, max:2026-03-25
Year min:2008, max:2026

In [ ]:
[jkldsjf]

In [75]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:lenon03@localhost/hr_project')

df.to_sql('hr_data', con=engine, if_exists='replace', index=False, chunksize=10000)

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)